import os
import sys
import time
import re
import urllib.parse
import requests
from playwright.sync_api import sync_playwright
from database import init_db, save_tweets

SESSION_PATH = os.path.join(os.path.dirname(__file__), "session.json")
TEMP_MEDIA_DIR = os.path.join(os.path.dirname(__file__), "temp_media")

# Konfigurasi Query Pencarian X — satu niche: AI
# 'use_live': True akan menggunakan tab 'Latest' (Terbaru) untuk mencari konten segar yang baru 1-2 jam
QUERIES_CONFIG = {
    "ai": {
        "query": '#AI OR "artificial intelligence" min_faves:300 lang:en',
        "lang": "en",
        "use_live": False
    }
}

def parse_metric_text(text):
    if not text:
        return 0
    match = re.search(r'([\d.,]+)\s*([KM]?)', text, re.IGNORECASE)
    if not match:
        return 0
    num_str = match.group(1).replace(',', '')
    unit = match.group(2).upper()
    try:
        val = float(num_str)
        if unit == 'K':
            return int(val * 1000)
        elif unit == 'M':
            return int(val * 1000000)
        return int(val)
    except ValueError:
        return 0

def create_cookie_file(session_path):
    """
    Parses cookies from playwright session.json and writes them in Netscape format.
    Returns the path to the temporary cookies.txt file.
    """
    if not os.path.exists(session_path):
        return None
        
    try:
        with open(session_path, 'r', encoding='utf-8') as f:
            session_data = json.load(f)
            
        cookies = session_data.get('cookies', [])
        if not cookies:
            return None
            
        cookie_file_path = os.path.join(os.path.dirname(session_path), "temp_cookies.txt")
        
        with open(cookie_file_path, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by bot\n\n")
            
            for c in cookies:
                domain = c.get('domain', '')
                include_subdomains = "TRUE" if domain.startswith('.') else "FALSE"
                path = c.get('path', '/')
                secure = "TRUE" if c.get('secure', False) else "FALSE"
                expiry = int(c.get('expires', 0))
                if expiry <= 0:
                    expiry = int(time.time() + 31536000)
                name = c.get('name', '')
                value = c.get('value', '')
                
                f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
                
        return cookie_file_path
    except Exception as e:
        print(f"Gagal membuat file cookies untuk yt-dlp: {e}")
        return None

def download_video(tweet_url, tweet_id, session_path):
    """
    Downloads video file from X to local temp_media folder using yt-dlp.
    """
    os.makedirs(TEMP_MEDIA_DIR, exist_ok=True)
    cookie_file = create_cookie_file(session_path)
    
    filename = f"{tweet_id}.mp4"
    local_path = os.path.join(TEMP_MEDIA_DIR, filename)
    abs_path = os.path.abspath(local_path)
    
    ydl_opts = {
        'outtmpl': local_path,
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'quiet': True,
        'no_warnings': True,
        'merge_output_format': 'mp4'
    }
    
    if cookie_file and os.path.exists(cookie_file):
        ydl_opts['cookiefile'] = cookie_file
        
    try:
        import yt_dlp
        print(f"Mengunduh video dari X menggunakan yt-dlp: {tweet_url} ...")
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([tweet_url])
        if os.path.exists(abs_path):
            print(f"Berhasil mengunduh video: {filename}")
            return abs_path
    except Exception as e:
        print(f"Gagal mengunduh video {tweet_url}: {e}")
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except Exception:
                pass
                
    return None

def download_media(url, tweet_id):
    """
    Downloads media file (image) from X to local temp_media folder.
    """
    if not url:
        return None
        
    os.makedirs(TEMP_MEDIA_DIR, exist_ok=True)
    
    # Deteksi ekstensi dari query params atau url
    ext = 'jpg'
    parsed_url = urllib.parse.urlparse(url)
    query_params = urllib.parse.parse_qs(parsed_url.query)
    
    if 'format' in query_params:
        ext = query_params['format'][0]
    elif '.png' in url.lower():
        ext = 'png'
    elif '.webp' in url.lower():
        ext = 'webp'
    elif '.gif' in url.lower():
        ext = 'gif'
        
    filename = f"{tweet_id}.{ext}"
    local_path = os.path.join(TEMP_MEDIA_DIR, filename)
    abs_path = os.path.abspath(local_path)
    
    # Lakukan pengunduhan berkas
    try:
        # Gunakan User-Agent standar agar tidak diblokir CDN X
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        }
        response = requests.get(url, headers=headers, timeout=15)
        if response.status_code == 200:
            with open(abs_path, 'wb') as f:
                f.write(response.content)
            print(f"Berhasil mengunduh media: {filename}")
            return abs_path
    except Exception as e:
        print(f"Gagal mengunduh media {url}: {e}")
    return None

def scrape_category_tweets(category, config, max_scrolls=3):
    if not os.path.exists(SESSION_PATH):
        print(f"Error: Berkas sesi '{SESSION_PATH}' tidak ditemukan. Jalankan login terlebih dahulu.")
        return []
        
    query = config["query"]
    lang = config["lang"]
    use_live = config.get("use_live", False)
    
    print(f"\n========================================================")
    print(f"SCRAPING KATEGORI: {category.upper()} ({lang.upper()})")
    print(f"Query: '{query}' | Tab: {'Latest (Live)' if use_live else 'Top'}")
    print(f"========================================================")
    
    scraped_data = []
    
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled"]
        )
        
        context = browser.new_context(
            storage_state=SESSION_PATH,
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
        context.add_init_script("delete navigator.__proto__.webdriver")
        
        page = context.new_page()
        
        encoded_query = urllib.parse.quote(query)
        # Jika use_live True, tambahkan parameter &f=live untuk mengambil postingan terbaru/segar
        search_url = f"https://x.com/search?q={encoded_query}"
        if use_live:
            search_url += "&f=live"
            
        page.goto(search_url)
        
        try:
            page.wait_for_selector('article[data-testid="tweet"]', timeout=10000)
        except Exception:
            print("Tidak ada tweet yang termuat untuk query ini.")
            browser.close()
            return []
            
        seen_ids = set()
        
        for scroll in range(max_scrolls):
            tweet_elements = page.query_selector_all('article[data-testid="tweet"]')
            
            for tweet in tweet_elements:
                try:
                    link_elem = tweet.query_selector('a[href*="/status/"]')
                    if not link_elem:
                        continue
                    
                    href = link_elem.get_attribute("href")
                    parts = href.split('/')
                    if len(parts) < 4:
                        continue
                    
                    author = parts[1]
                    tweet_id = parts[3]
                    
                    if tweet_id in seen_ids:
                        continue
                    seen_ids.add(tweet_id)
                    
                    # Verifikasi umur tweet (tidak boleh lebih dari 48 jam)
                    time_elem = tweet.query_selector('time')
                    if time_elem:
                        datetime_str = time_elem.get_attribute("datetime")
                        if datetime_str:
                            from datetime import datetime, timezone
                            try:
                                cleaned_dt = datetime_str.replace('Z', '+00:00')
                                tweet_time = datetime.fromisoformat(cleaned_dt)
                                now_time = datetime.now(timezone.utc)
                                age_hours = (now_time - tweet_time).total_seconds() / 3600.0
                                if age_hours > 48.0:
                                    continue
                            except Exception as e:
                                print(f"Gagal memparsing waktu tweet {tweet_id}: {e}")
                    
                    # Teks tweet
                    text_elem = tweet.query_selector('[data-testid="tweetText"]')
                    text = text_elem.inner_text() if text_elem else ""
                    if not text:
                        continue
                        
                    # Metrik likes & retweets
                    like_elem = tweet.query_selector('[data-testid="like"]')
                    like_label = like_elem.get_attribute("aria-label") if like_elem else ""
                    likes = parse_metric_text(like_label)
                    
                    retweet_elem = tweet.query_selector('[data-testid="retweet"]')
                    retweet_label = retweet_elem.get_attribute("aria-label") if retweet_elem else ""
                    retweets = parse_metric_text(retweet_label)
                    
                    # Cek apakah tweet memiliki video
                    video_elem = tweet.query_selector('video') or tweet.query_selector('div[data-testid="videoPlayer"]')
                    local_media_path = None
                    media_urls = []
                    
                    if video_elem:
                        tweet_url = f"https://x.com/{author}/status/{tweet_id}"
                        local_media_path = download_video(tweet_url, tweet_id, SESSION_PATH)
                        if local_media_path:
                            media_urls = [tweet_url]
                            
                    if not local_media_path:
                        # Cari media gambar
                        media_elems = tweet.query_selector_all('img[src*="/media/"]')
                        media_urls = [elem.get_attribute("src") for elem in media_elems if elem.get_attribute("src")]
                        
                        # Unduh media pertama jika ada
                        if media_urls:
                            # Ambil media pertama saja untuk postingan
                            local_media_path = download_media(media_urls[0], tweet_id)
                    
                    tweet_info = {
                        "id": tweet_id,
                        "author": author,
                        "text": text,
                        "likes": likes,
                        "retweets": retweets,
                        "media_urls": media_urls,
                        "local_media_path": local_media_path
                    }
                    scraped_data.append(tweet_info)
                    
                except Exception:
                    continue
            
            # Scroll down
            page.evaluate("window.scrollBy(0, 1000)")
            time.sleep(1.5)
            
        browser.close()
        
    # Simpan ke database
    if scraped_data:
        saved = save_tweets(scraped_data, category=category, language=lang)
        print(f"Berhasil menyimpan/mengupdate {saved} tweet di kategori {category}.")
        
    return scraped_data

def run_all_scraping():
    init_db()
    
    # Kosongkan antrean lama sebelum memulai scraping harian baru
    from database import reset_pending_queue
    reset_pending_queue()
    
    total_saved = 0
    for category, config in QUERIES_CONFIG.items():
        try:
            results = scrape_category_tweets(category, config)
            total_saved += len(results)
            # Berikan jeda antar-kategori agar tidak memicu deteksi bot X
            time.sleep(random_delay := float(time.time() % 3 + 2))
        except Exception as e:
            print(f"Error scraping kategori {category}: {e}")
            
    print(f"\n========================================================")
    print(f"SELESAI. Total tweet diproses pada seluruh kategori: {total_saved}")
    print(f"========================================================")

if __name__ == "__main__":
    run_all_scraping()
